---
- name: Remove mail packages not necessary
  ansible.builtin.apt:
      name: [bsd-mailx mailutils postfix]
      autoremove: true
      state: absent
  when: ansible_os_family == "Debian"

- name: Check that ssmtp is installed
  ansible.builtin.package:
      name: ssmtp
      state: present

- name: Check that sendmail redirects to ssmtp
  ansible.builtin.file:
      src: ssmtp
      dest: /usr/sbin/sendmail
      force: true
      owner: root
      group: mail
      state: link

- name: Configuration file for ssmtp
  ansible.builtin.template:
      src: ssmtp.conf.j2
      dest: /etc/ssmtp/ssmtp.conf
      owner: root
      group: mail
      mode: '0640'
